"""
config.py
---------
Holds global configuration variables, such as:
    - Sample rate, hop length, bins per octave.
    - Dataset directories.
    - Training hyperparameters (batch size, learning rate, etc.).
"""

SAMPLE_RATE = ...
HOP_LENGTH = ...
BINS_PER_OCTAVE = ...
N_PITCHES = ...

DATASET_DIR = ...
PROCESSED_DIR = ...

BATCH_SIZE = ...
LEARNING_RATE = ...
EPOCHS = ...
